# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c22f5a72e816cc69e1d4519387b852ec0d5f88aef51d0f70ecf009ea58c0a6f740404029a3b5d23ca40bb86a1e48aa6f280cd31a19af2159b178814d90121d2

test:
  secret_key_base: f9d426930b62df8443e516373bbe9b82dd510c94018cc169d7e8c22cb9baead1314300d0534218e90b011711c589a04722fe5c1b81c422a9f17c526ea3198c3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
